### ISSUE TITLE
Error on plot.parkvisits 

### ISSUE THREAD

**Issue by DrMattG** [befriendabacterium/parksinthepandemic#120]
https://github.com/befriendabacterium/parksinthepandemic/tree/Plotparks_Matt

Warning: Error in UseMethod: no applicable method for 'predict' applied to an object of class "randomForest"

Is this a :: issue?

**Comment by befriendabacterium** [comment]
Sorry that needs correcting. Load randomforest library and will work

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by befriendabacterium** [comment]
Fixed...that was a weird one!
https://github.com/befriendabacterium/parksinthepandemic/pull/122
