### ISSUE TITLE
Change last line of read.metofficedata.R function so it doesn't create object within function

### ISSUE THREAD

**Issue by befriendabacterium** [befriendabacterium/parksinthepandemic#14]

**Comment by befriendabacterium** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make a Met Office data downloader function](https://trello.com/c/VkYEGztE/133-make-a-met-office-data-downloader-function)

**Comment by sk608** [comment]
I've just removed the objects and pushed them both to GitHub

**Comment by sk608** [comment]
Ahh Just realised I need to get rid of an argument on the downloader function, sorry about that was re-running it so I could set up the next code!
