### ISSUE TITLE
Make a function for plotting the bar graphs of park mobility vs time

### ISSUE THREAD

**Issue by sk608** [befriendabacterium/parksinthepandemic#15]

**Comment by sk608** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make a bar chart creator function for the google mobility data.](https://trello.com/c/XWg9JUO3/137-make-a-bar-chart-creator-function-for-the-google-mobility-data)

**Comment by befriendabacterium** [comment]
have just renamed this to be less specific - at this stage dont need the extra functionality
