### ISSUE TITLE
Add example workflow to functions

### ISSUE THREAD

**Issue by DrMattG** [befriendabacterium/parksinthepandemic#24]
Can you add a worked reproducible example of plot.mobilitydata() - I can not get it to run and I cant work out why (I think I have loaded the correct libraries but maybe not pointing at the right dataset?). Do we want to have the Shiny get the data each time it is run or to save the data periodically (slowness versus painful and continued developer time)? If we want continuous link to the mobility data can you also give a reproducible example of plot.mobilitydata() too as I can get it to work but not sure why I cant reproduce your plots.... maybe just one of those days!

**Comment by befriendabacterium** [comment]
Hi Matt - just fixed this. It wasn't outputting the plot object as part of the function. Added example workflow from the main directory. Also added an example mobility report to the data/google folder. For now, avoid sourcing the latest report and just use the example in data/google. Longer-term, we'll add a button to update everything, perhaps?

**Comment by befriendabacterium** [comment]
Please confirm that you can reproduce using newly-named plot.googlemobility()

**Comment by befriendabacterium** [comment]
Also could I get your advice on where the required packages for each function should go? within the function? a seperate script of required packages that is sourced in the function? I'm a bit unclear on this and how it all packages up in the end

**Comment by DrMattG** [comment]
I get this error:  "Error in tapply(Data[, Loc], list(Data$sub_country, Data$date), std.error,  : 
  object 'std.error' not found". 

Packages can for the moment just go in the function: a_function<-function(x){
library(Y)
function_things
} 
When I package it up I will add all the libraries to the package DESCRIPTION file and take them out of the functions. To save me some time you could use :: within each function (e.g. ggplot2::ggplot(); dplyr::summarise())

**Comment by befriendabacterium** [comment]
Ah, sloppy of me. Sorry. I forgot to load plotrix for the std.error() function.

As a quick workaround to avoid having to go through and :: everything, i've created a requiredpackages.R file and sourced this in each function for now.

Can you run it?

**Comment by befriendabacterium** [comment]
Wait this won't work...one sec

**Comment by DrMattG** [comment]
That works! I'll have to :: everything when it comes to packaging it up I think otherwise we will hit problems when building. But that is not too much of a problem to do. I think there are some shortcuts.

**Comment by DrMattG** [comment]
> "Wait this won't work...one sec"

Yeah it's not a function! :)

**Comment by befriendabacterium** [comment]
Blegh! Well glad you got it running...lemme correct this then i'll resolve. Will to the :: from now on and tidy up the old ones
