### ISSUE TITLE
Added BN example to ForScarlett branch

### ISSUE THREAD

**Issue by DrMattG** [befriendabacterium/parksinthepandemic#32]
@sk608 I have added the BN example to https://github.com/befriendabacterium/parksinthepandemic/tree/ForScarlett

I have not had enough time to fully comment the code (sorry) but it should give you an idea of my thinking. The last plot is the sort of hypothetical outcome plot I was thinking about. We can put this in to shiny so that a user chooses region, day, weather, etc and then we output the probability that it will be higher or lower than baseline. We probably need to think about how to make the graphs reader friendly - this could be another way of plotting (a single point estimate with credible intervals might be one way, adding descriptive text is quite effective). If it doesn't work or something is not clear then let me know. Also I struggled with adding rain in - something weird with the data (hidden "Inf" in the data - not sure where this comes from but we can sort that later).

@befriendabacterium FYI

![image](https://user-images.githubusercontent.com/11541781/86743163-f9cec280-c038-11ea-8dcf-9f09e3cf7534.png)

**Comment by befriendabacterium** [comment]
Hi Matt - thanks for this! This is an interesting new way of visualising this, I like it. Will take a look at this once and your analysis in more detail once have got through the other issues that have just piled up ahahha. cheers
