### ISSUE TITLE
Solve boundaries plotting issues in leaflet (file too large to plot)

### ISSUE THREAD

**Issue by befriendabacterium** [befriendabacterium/parksinthepandemic#37]

**Comment by DrMattG** [comment]
@befriendabacterium can you point me to the file - there is a way to simplify shapefiles to allow easier plotting with leaflet

**Comment by befriendabacterium** [comment]
Yeah hang fire one sec, it’s been uploading to OSF for a couple of hours lol. Gonna make a function to read it in then you’re good to do your thang

**Comment by befriendabacterium** [comment]
Yeah hang fire still trying to get the bloody shapefile to OSF but the OSF Storage in Germany server keeps dropping

**Comment by JHHatfield** [comment]
If it is just for plotting would st_simplify() work?

**Comment by befriendabacterium** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Plot Google boundaries on the app map](https://trello.com/c/5gO9Fulh/172-plot-google-boundaries-on-the-app-map)

**Comment by DrMattG** [comment]
Managed to map the boundaries shape
