### ISSUE TITLE
Read Google boundaries shapefile into app from OSF

### ISSUE THREAD

**Issue by befriendabacterium** [befriendabacterium/parksinthepandemic#38]

**Comment by JHHatfield** [comment]
Can the files just be stored on the server running the shiny?

**Comment by befriendabacterium** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Plot Google boundaries on the app map](https://trello.com/c/5gO9Fulh/172-plot-google-boundaries-on-the-app-map)
