### ISSUE TITLE
Get median for Met Office weather over 5 weeks not per day

### ISSUE THREAD

**Issue by befriendabacterium** [befriendabacterium/parksinthepandemic#66]

**Comment by sk608** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make changes to the relative2baseline code](https://trello.com/c/hbiXeU4A/190-make-changes-to-the-relative2baseline-code)

**Comment by sk608** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make changes to the relative2baseline code](https://trello.com/c/hbiXeU4A/190-make-changes-to-the-relative2baseline-code)
