### ISSUE TITLE
Fix scaling bug with y axis (see image)

### ISSUE THREAD

**Issue by befriendabacterium** [befriendabacterium/parksinthepandemic#94]
<img width="396" alt="yaxis_scalebug" src="https://user-images.githubusercontent.com/42059798/87668240-ae689280-c763-11ea-87ba-d898c4728491.png">

**Comment by DrMattG** [comment]
@befriendabacterium you just need to change a line in plot.googlemobilitydistricts to 
#Limits the size of the graph.    coord_cartesian(ylim=c(min(Data$parks_percent_change_from_baseline),max(Data$parks_percent_change_from_baseline))) +

**Comment by befriendabacterium** [comment]
Have just edited this. What I actually decided was best to have is the ymin/ymax as the min/max of the park visits for the WHOLE dataset (not the current district). This allows users to easily compare the timelines of different districts without misleading them into thinking that Bedford's fluctuations are on the same scale as Dorset's, for example.

However, I can't get this to work by grabbing the min and max from the WHOLE google park data and then setting this as the ymin/ymax. When I do, it seems to just ignore it and do it per-district. Weird. Something to do with reactivity, perhaps? But I can't figure it out. So i've just manually set ymin/max to -100 and 400 for now (committed to develop). If anyone can figure out how to do it more robustly so that if we update the google data and the max is now +500% for example, that'd be great! Cos i'm stumped!

Cheers
Matt
